# Generated by Django 3.2.9 on 2021-11-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='作者', max_length=100)),
                ('author_id', models.CharField(verbose_name='原始_ id', max_length=100)),
                ('desc', models.TextField(default='', verbose_name='作者描述', max_length=4096, null=True)),
                ('dynasty', models.IntegerField(choices=[(0, '未知'), (1, '唐'), (2, '宋'), (3, '元'), (4, '明'), (5, '清')], verbose_name='作者所处年代')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '古诗作者',
                'ordering': ['id', '-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SongCi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(verbose_name='宋词作者', max_length=300)),
                ('title', models.CharField(verbose_name='宋词标题', max_length=300)),
                ('paragraphs', models.TextField(verbose_name='宋词内容', max_length=5000)),
                ('poet_id', models.CharField(verbose_name='宋词原始_ id', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_change_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('tag', models.CharField(verbose_name='宋词tag', max_length=300, null=True)),
            ],
            options={
                'verbose_name': '宋词',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Strains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strains', models.TextField(verbose_name='宋词内容', max_length=5000)),
                ('poet_id', models.CharField(verbose_name='宋词原始_ id', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_change_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'verbose_name': '节奏，押韵',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TangShi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(verbose_name='古诗作者', max_length=300)),
                ('title', models.CharField(verbose_name='古诗标题', max_length=300)),
                ('paragraphs', models.TextField(verbose_name='古诗内容', max_length=5000)),
                ('poet_id', models.CharField(verbose_name='古诗原始_ id', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_change_date', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('tag', models.CharField(verbose_name='古诗tag', max_length=300, null=True)),
            ],
            options={
                'verbose_name': '唐诗',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TangShiSanBai',
            fields=[
                ('TangShi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gushi.TangShi')),
            ],
            options={
                'verbose_name': '唐诗三百首',
                'ordering': ['id'],
            },
            bases=('gushi.TangShi',),
        ),
    ]
