# Generated by Django 3.2.9 on 2021-11-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gushi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='TangShi',
            old_name='tag',
            new_name='tags',
        ),
    ]
