# Generated by Django 3.2.9 on 2021-11-19 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gushi', '0002_rename_tag_tangshi_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCiSanBai',
            fields=[
                ('songci_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gushi.songci')),
            ],
            options={
                'verbose_name': '宋词三百首',
                'ordering': ['id'],
            },
            bases=('gushi.songci',),
        ),
    ]
