# Generated by Django 3.2.9 on 2021-11-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gushi', '0003_songcisanbai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songci',
            old_name='tag',
            new_name='tags',
        ),
    ]
