# Generated by Django 3.2.9 on 2021-11-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gushi', '0005_auto_20211119_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuShiPinYins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_pinyin', models.CharField(max_length=300, null=True, verbose_name='宋词作者_pinyin')),
                ('title_pinyin', models.CharField(max_length=300, null=True, verbose_name='宋词标题_pinyin')),
                ('paragraphs_pinyin', models.TextField(max_length=5000, null=True, verbose_name='宋词内容_pinyin')),
            ],
            options={
                'verbose_name': '拼音 表',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='songci',
            name='author_pinyin',
        ),
        migrations.RemoveField(
            model_name='songci',
            name='paragraphs_pinyin',
        ),
        migrations.RemoveField(
            model_name='songci',
            name='title_pinyin',
        ),
        migrations.RemoveField(
            model_name='tangshi',
            name='author_pinyin',
        ),
        migrations.RemoveField(
            model_name='tangshi',
            name='paragraphs_pinyin',
        ),
        migrations.RemoveField(
            model_name='tangshi',
            name='title_pinyin',
        ),
        migrations.AddField(
            model_name='songci',
            name='pinyi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gushi.gushipinyins', verbose_name='拼音'),
        ),
        migrations.AddField(
            model_name='tangshi',
            name='pinyi',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gushi.gushipinyins', verbose_name='拼音'),
        ),
    ]
