# Generated by Django 3.2.9 on 2021-11-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gushi', '0007_auto_20211119_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songci',
            old_name='pinyi',
            new_name='pinyin',
        ),
        migrations.RenameField(
            model_name='tangshi',
            old_name='pinyi',
            new_name='pinyin',
        ),
    ]
