# Generated by Django 3.2.9 on 2021-11-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gushi', '0010_auto_20211122_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gushipinyins',
            name='author_pinyin',
            field=models.CharField(max_length=300, null=True, verbose_name='作者_pinyin'),
        ),
        migrations.AlterField(
            model_name='gushipinyins',
            name='paragraphs_pinyin',
            field=models.TextField(max_length=5000, null=True, verbose_name='内容_pinyin'),
        ),
        migrations.AlterField(
            model_name='gushipinyins',
            name='title_pinyin',
            field=models.CharField(max_length=300, null=True, verbose_name='标题_pinyin'),
        ),
    ]
