# Generated by Django 3.2.9 on 2021-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gushi', '0012_lunyu_shijing_yuanqu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shijing',
            name='dynasty',
        ),
        migrations.AlterField(
            model_name='yuanqu',
            name='dynasty',
            field=models.CharField(max_length=100, verbose_name='元曲'),
        ),
    ]
