"""
Django settings for shiciServer project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
import environ
import pymysql

pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_DIR = environ.Path(__file__)

env = environ.Env(
    # set casting, default value
    # DEBUG=(bool, False)
)

# reading .env file
env.read_env(os.path.join(BASE_DIR, 'env/.local'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('SHICIDEBUG')

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'gushi.apps.GushiConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shiciServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shiciServer.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env.str('SHICI_NAME'),
        'HOST': env.str('SHICI_HOST'),
        'USER': env.str('SHICI_USER'),
        'PASSWORD': env.str('SHICI_PAD'),
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'PAGE_SIZE': 20,
    'DEFAULT_PAGINATION_CLASS': 'gushi.utils.custom_pagination.LargeResultsSetPagination',
    'EXCEPTION_HANDLER': 'gushi.utils.custom_exception.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
}
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 中文支持，django1.8以后支持；1.8以前是zh-cn

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 默认是Ture，时间是utc时间，由于我们要用本地时间，所用手动修改为false！！！！

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGS_DIR = os.path.join(BASE_DIR, 'logs')  # 配置日志路径

# 配置日志
DEBUG_LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # 详细的日志格式
        # 'standard': {
        #     'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d]'
        #               '[%(levelname)s][%(message)s]'
        # },
        'verbose': {
            # 输出日志级别名称，日志消息以及生成日志消息的时间，进程，线程和模块
            # 'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s',
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d][%(levelname)s][%(message)s]',
            'datefmt': "%Y-%m-%d %H:%M:%S"
        },
        'simple': {  # 定义命名为 simple 的格式化
            'format': '%(levelname)s %(asctime)s %(message)s'  # 仅输出日志级别名称（例如 DEBUG）和日志消息。
        },
    },
    'handlers': {
        # 定义命名为 console 的处理器，将INFO级别的日志使用 stream 流处理打印到控制台
        'console': {
            'level': 'DEBUG',  # INFO DEBUG
            'class': 'logging.StreamHandler',
            'formatter': 'simple'  # 使用 simple，只输出日志等级以及 messages 信息
        },
        # loggings 单进程的配置方式：输出日志到文件，按日期滚动
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            # TimedRotatingFileHandler的参数
            # 参照https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler
            # 目前设定每天一个日志文件
            'filename': 'logs/debug/loggerpratice.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 100,
            'formatter': 'verbose',  # 使用复杂的verbose详细信息输出
            'encoding': 'utf-8'  # 设置utf8编码，避免中文乱码
        },

        # windows下 多进程的配置方式：使用concurrent_log_handler
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
        #     'filename': os.path.join(LOGS_DIR, 'app.log'),
        #     'maxBytes': 1024 * 1024 * 10,  # 当达到10MB时分割日志
        #     'backupCount': 50,  # 最多保留50份文件
        #     'formatter': 'verbose',  # 使用复杂的verbose详细信息输出
        #     'encoding': 'utf-8'  # 设置utf8编码，避免中文乱码
        # },

        # linux下 多进程的配置方式：使用ConcurrentLogHandler
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'cloghandler.ConcurrentRotatingFileHandler',
        #     'filename': os.path.join(LOGS_DIR, 'app.log'),
        #     'maxBytes': 1024 * 1024 * 10,  # 当达到10MB时分割日志
        #     'backupCount': 50,  # 最多保留50份文件
        #     'formatter': 'verbose',  # 使用复杂的verbose详细信息输出
        #     # If delay is true,
        #     # then file opening is deferred until the first call to emit().
        #     'delay': True,
        #     'encoding': 'utf-8'  # 设置utf8编码，避免中文乱码
        # },

        # 发送邮件，目前腾讯云、阿里云的服务器对外发送邮件都有限制，暂时不使用
        'email': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    'loggers': {
        # 不同的logger
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            # 'level': 'DEBUG',  # 日志的等级为 debug
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
PRO_LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # 详细的日志格式
        # 'standard': {
        #     'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d]'
        #               '[%(levelname)s][%(message)s]'
        # },
        'verbose': {
            # 输出日志级别名称，日志消息以及生成日志消息的时间，进程，线程和模块
            # 'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s',
            'format': '[%(asctime)s][%(threadName)s:%(thread)d][task_id:%(name)s][%(filename)s:%(lineno)d][%(levelname)s][%(message)s]',
            'datefmt': "%Y-%m-%d %H:%M:%S"
        },
        'simple': {  # 定义命名为 simple 的格式化
            'format': '%(levelname)s %(asctime)s %(message)s'  # 仅输出日志级别名称（例如 DEBUG）和日志消息。
        },
    },
    'handlers': {
        # 定义命名为 console 的处理器，将INFO级别的日志使用 stream 流处理打印到控制台
        'console': {
            'level': 'DEBUG',  # INFO DEBUG
            'class': 'logging.StreamHandler',
            'formatter': 'simple'  # 使用 simple，只输出日志等级以及 messages 信息
        },
        # loggings 单进程的配置方式：输出日志到文件，按日期滚动
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            # TimedRotatingFileHandler的参数
            # 参照https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler
            # 目前设定每天一个日志文件
            'filename': 'logs/pro/loggerpratice.log',
            'when': 'midnight',
            'interval': 1,
            'backupCount': 100,
            'formatter': 'verbose',  # 使用复杂的verbose详细信息输出
            'encoding': 'utf-8'  # 设置utf8编码，避免中文乱码
        },

        # windows下 多进程的配置方式：使用concurrent_log_handler
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'concurrent_log_handler.ConcurrentRotatingFileHandler',
        #     'filename': os.path.join(LOGS_DIR, 'app.log'),
        #     'maxBytes': 1024 * 1024 * 10,  # 当达到10MB时分割日志
        #     'backupCount': 50,  # 最多保留50份文件
        #     'formatter': 'verbose',  # 使用复杂的verbose详细信息输出
        #     'encoding': 'utf-8'  # 设置utf8编码，避免中文乱码
        # },

        # linux下 多进程的配置方式：使用ConcurrentLogHandler
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'cloghandler.ConcurrentRotatingFileHandler',
        #     'filename': os.path.join(LOGS_DIR, 'app.log'),
        #     'maxBytes': 1024 * 1024 * 10,  # 当达到10MB时分割日志
        #     'backupCount': 50,  # 最多保留50份文件
        #     'formatter': 'verbose',  # 使用复杂的verbose详细信息输出
        #     # If delay is true,
        #     # then file opening is deferred until the first call to emit().
        #     'delay': True,
        #     'encoding': 'utf-8'  # 设置utf8编码，避免中文乱码
        # },

        # 发送邮件，目前腾讯云、阿里云的服务器对外发送邮件都有限制，暂时不使用
        'email': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    'loggers': {
        # 不同的logger
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            # 'level': 'DEBUG',  # 日志的等级为 debug
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
if DEBUG:
    LOGGING = DEBUG_LOGGING
else:
    LOGGING = PRO_LOGGING
